export const COUNTRY_OPTIONS = [
  { value: 'CI', label: "Côte d'Ivoire" },
  { value: 'SN', label: 'Sénégal' },
  { value: 'CM', label: 'Cameroun' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'ML', label: 'Mali' },
  { value: 'GN', label: 'Guinée' },
  { value: 'GW', label: 'Guinée-Bissau' },
  { value: 'TG', label: 'Togo' },
  { value: 'BJ', label: 'Bénin' },
  { value: 'GH', label: 'Ghana' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NE', label: 'Niger' },
  { value: 'TD', label: 'Tchad' },
  { value: 'GA', label: 'Gabon' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'République démocratique du Congo' },
  { value: 'CF', label: 'République centrafricaine' },
  { value: 'BI', label: 'Burundi' },
  { value: 'RW', label: 'Rwanda' },
  { value: 'UG', label: 'Ouganda' },
  { value: 'KE', label: 'Kenya' },
  { value: 'TZ', label: 'Tanzanie' },
  { value: 'ET', label: 'Éthiopie' },
  { value: 'SO', label: 'Somalie' },
  { value: 'SD', label: 'Soudan' },
  { value: 'SS', label: 'Soudan du Sud' },
  { value: 'DJ', label: 'Djibouti' },
  { value: 'ER', label: 'Érythrée' },
  { value: 'ZA', label: 'Afrique du Sud' },
  { value: 'NA', label: 'Namibie' },
  { value: 'BW', label: 'Botswana' },
  { value: 'ZW', label: 'Zimbabwe' },
  { value: 'ZM', label: 'Zambie' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'LS', label: 'Lesotho' },
  { value: 'SZ', label: 'Eswatini' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MU', label: 'Maurice' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'KM', label: 'Comores' },
  { value: 'ST', label: 'Sao Tomé-et-Principe' },
  { value: 'LY', label: 'Libye' },
  { value: 'TN', label: 'Tunisie' },
  { value: 'DZ', label: 'Algérie' },
  { value: 'MA', label: 'Maroc' },
  { value: 'MR', label: 'Mauritanie' },
  { value: 'CV', label: 'Cap-Vert' },
  { value: 'AO', label: 'Angola' },
  { value: 'EH', label: 'Sahara occidental' },
  { value: 'FR', label: 'France' },
  { value: 'BE', label: 'Belgique' },
  { value: 'CH', label: 'Suisse' },
  { value: 'CA', label: 'Canada' },
  { value: 'US', label: 'États-Unis' },
  { value: 'GB', label: 'Royaume-Uni' },
  { value: 'ES', label: 'Espagne' },
  { value: 'PT', label: 'Portugal' },
  { value: 'DE', label: 'Allemagne' },
  { value: 'IT', label: 'Italie' },
  { value: 'CN', label: 'Chine' },
  { value: 'IN', label: 'Inde' },
  { value: 'BR', label: 'Brésil' },
  { value: 'AE', label: 'Émirats arabes unis' },
  { value: 'QA', label: 'Qatar' },
];
