apiVersion: 1

contactPoints:
  - orgId: 1
    name: forges-team-email
    receivers:
      - uid: forges-email-receiver
        type: email
        settings:
          addresses: ${ALERT_EMAIL_RECIPIENTS:-admin@forges-group.com}
          singleEmail: true
        disableResolveMessage: false
